# Generated by Django 5.2.5 on 2025-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
