# Generated by Django 5.2.6 on 2025-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_capital_country_topleveldomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='topLevelDomain',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
